(() => {
'use strict';
const ENDPOINT='https://mjxytssjgavwfcypoyti.supabase.co/functions/v1/workout-coach';
const ANON='sb_publishable_O4XRvCgQXMyn1ulMslutdQ_Fdz38KPO';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
let busy=false,baseTab=null,baseWorkouts=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=v=>JSON.parse(JSON.stringify(v));
function initState(){
 if(typeof state==='undefined')return false;
 state.coach??={}; state.coach.messages??=[]; state.coach.proposal??=null; state.coachOverrides??={};
 state.coach.profile??={goals:['Build chest, biceps and core','Gradual fat loss','Improve flexibility, mobility and knee stability'],equipment:'Planet Fitness machines, cables, Smith machine, leg press and dumbbells',constraints:['Prior ACL tear and meniscus surgery','Avoid jumping, quick lateral movement, deep knee flexion, free-weight squats and heavy isolated knee pressure','Prefer controlled low-impact exercise']};
 return true;
}
function key(day,pid,week){return `${pid||(typeof getActiveProgramId==='function'?getActiveProgramId():state.programId)}|${parseInt(week||state.week||1,10)}|${day}`}
function installWorkoutAdapter(){
 if(baseWorkouts||typeof window.getWorkoutsForDay!=='function')return;
 baseWorkouts=window.getWorkoutsForDay;
 window.getWorkoutsForDay=(day,pid=null,week=null)=>clone(state.coachOverrides[key(day,pid,week)]?.exercises||baseWorkouts(day,pid,week));
}
function install(){
 if(!initState()){setTimeout(install,100);return}
 if(document.getElementById('coachTabBtn'))return;
 const style=document.createElement('style');style.textContent=`
 .coach-only{display:none}.tab-coach .home-only,.tab-coach .program-only,.tab-coach .history-only{display:none!important}.tab-coach .coach-only{display:block!important}
 .coach{max-width:760px;margin:auto;padding-bottom:6rem}.coach-card,.coach-msg,.coach-plan,.coach-compose{background:var(--bg2);border:1px solid var(--border);border-radius:14px;padding:.8rem;margin-bottom:.65rem}.coach-head{display:flex;justify-content:space-between;gap:.5rem}.coach-head h2{font-family:var(--font-display);letter-spacing:.05em}.coach-note,.coach-meta{font-size:.68rem;color:var(--text3);line-height:1.45}.coach-privacy{background:rgba(245,204,90,.1)}
 .coach-msg{max-width:88%;font-size:.78rem;line-height:1.5}.coach-msg.user{margin-left:auto;background:var(--accent);color:#10140d}.coach-msg.error{color:var(--red)}.coach-empty{text-align:center;color:var(--text3);padding:1.5rem;font-size:.78rem}.coach-plan{border-color:var(--accent)}.coach-ex{display:flex;justify-content:space-between;gap:.5rem;padding:.35rem 0;border-top:1px solid var(--border);font-size:.7rem}.coach-ex small{display:block;color:var(--text3)}
 .coach-btn,.coach-chip{border:1px solid var(--border);background:var(--bg3);color:var(--text);border-radius:9px;padding:.45rem .65rem;font:700 .68rem var(--font-body);cursor:pointer}.coach-btn.primary{background:var(--accent);color:#10140d}.coach-actions,.coach-chips{display:flex;gap:.4rem;flex-wrap:wrap}.coach-chips{margin-bottom:.65rem}.coach-compose{position:sticky;bottom:.5rem}.coach-row{display:flex;gap:.45rem}.coach-input{flex:1;min-height:44px;max-height:120px;resize:none;background:var(--bg3);color:var(--text);border:1px solid var(--border);border-radius:10px;padding:.6rem;font:inherit}.coach-send{width:44px;border:0;border-radius:10px;background:var(--accent);font-size:1rem}.coach-input:disabled,.coach-send:disabled{opacity:.5}.coach-active{display:flex;justify-content:space-between;align-items:center;border-color:var(--accent2)}
 @media(max-width:640px){.top-tabs-inner{overflow-x:auto;justify-content:flex-start}.top-tab{flex:0 0 auto}.coach-msg{max-width:95%}}
 `;document.head.appendChild(style);
 const tab=document.createElement('button');tab.id='coachTabBtn';tab.className='top-tab';tab.innerHTML='&#129302; Coach';tab.onclick=()=>setActiveTab('coach');document.querySelector('.top-tabs-inner')?.appendChild(tab);
 const area=document.createElement('div');area.id='coachArea';area.className='content coach-only';document.getElementById('appShell')?.appendChild(area);
 baseTab=window.setActiveTab; window.setActiveTab=tabName=>{if(tabName!=='coach'){document.body.classList.remove('tab-coach');tab.classList.remove('active');return baseTab(tabName)}document.querySelectorAll('.top-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.body.classList.remove('tab-program','tab-history');document.body.classList.add('tab-coach');render()};
 installWorkoutAdapter();
}
function day(){return DAYS.includes(state.day)?state.day:(typeof getActiveEditableWorkoutDay==='function'?getActiveEditableWorkoutDay():new Date().toLocaleDateString('en-US',{weekday:'long'}))}
function msgHtml(m){return `<div class="coach-msg ${m.role}">${esc(m.text).replace(/\n/g,'<br>')}<div class="coach-meta">${new Date(m.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></div>`}
function proposalHtml(p){return `<div class="coach-plan"><div class="coach-head"><div><strong>${esc(p.title||`Adjusted ${p.day}`)}</strong><div class="coach-note">${esc(p.reason||'Coach adjustment')}</div></div><span class="coach-meta">Needs approval</span></div><div>${p.exercises.map(e=>`<div class="coach-ex"><div><b>${esc(e.exercise)}</b><small>${esc(e.phase)}${e.notes?' · '+esc(e.notes):''}</small></div><b>${esc(e.sets)} × ${esc(e.reps)}</b></div>`).join('')}</div><div class="coach-actions"><button class="coach-btn" id="dismissCoach">Dismiss</button><button class="coach-btn primary" id="applyCoach">Apply to ${esc(p.day)}</button></div></div>`}
function render(){
 initState();const area=document.getElementById('coachArea');if(!area)return;const d=day(),override=state.coachOverrides[key(d)],ok=state.coach.privacyAccepted===true;
 area.innerHTML=`<div class="coach"><div class="coach-card"><div class="coach-head"><div><h2>AI WORKOUT COACH</h2><div class="coach-note">Uses your program and recent workout history. It cannot change your schedule until you approve a proposal.</div></div><b class="coach-meta">Gemini Flash</b></div></div><div class="coach-card coach-privacy"><div class="coach-note">Gemini's free tier may use prompts and responses to improve Google products. Your name, PIN and sync key are not sent to Gemini.</div><label class="coach-note"><input id="coachConsent" type="checkbox" ${ok?'checked':''}> I understand and want to test using my non-identifying workout information.</label></div>${override?`<div class="coach-card coach-active"><div><b>Coach plan active for ${esc(d)}</b><div class="coach-note">${esc(override.title||override.reason)}</div></div><button class="coach-btn" id="undoCoach">Undo</button></div>`:''}<div class="coach-chips"><button class="coach-chip" data-q="Adjust my ${esc(d)} workout to fit in 45 minutes.">45-minute workout</button><button class="coach-chip" data-q="My knees feel stiff today. Review my workout and recommend a knee-safe adjustment.">Knees feel stiff</button><button class="coach-chip" data-q="Review my recent progress and tell me where I am stalling.">Review progress</button></div><div id="coachMessages">${state.coach.messages.length?state.coach.messages.slice(-30).map(msgHtml).join(''):'<div class="coach-empty">Ask about today’s workout, soreness, missed days, substitutions, progression or your goals.</div>'}${busy?'<div class="coach-msg assistant">Thinking…</div>':''}</div>${state.coach.proposal?proposalHtml(state.coach.proposal):''}<div class="coach-compose"><div class="coach-row"><textarea id="coachInput" class="coach-input" maxlength="2000" placeholder="What do you need today?" ${!ok||busy?'disabled':''}></textarea><button id="coachSend" class="coach-send" ${!ok||busy?'disabled':''}>&#10148;</button></div><div class="coach-meta">${currentSyncKey?'Synced profile connected.':'Sign in to sync before using Coach.'} <button class="coach-btn" id="clearCoach">Clear chat</button></div></div></div>`;
 document.getElementById('coachConsent')?.addEventListener('change',e=>{state.coach.privacyAccepted=e.target.checked;save();render()});
 document.querySelectorAll('.coach-chip').forEach(b=>b.onclick=()=>{const i=document.getElementById('coachInput');i.value=b.dataset.q;i.focus()});
 document.getElementById('coachSend')?.addEventListener('click',send);document.getElementById('coachInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
 document.getElementById('clearCoach')?.addEventListener('click',()=>{if(!state.coach.messages.length||confirm('Clear coach chat?')){state.coach.messages=[];state.coach.proposal=null;save();render()}});
 document.getElementById('dismissCoach')?.addEventListener('click',()=>{state.coach.proposal=null;save();render()});document.getElementById('applyCoach')?.addEventListener('click',apply);document.getElementById('undoCoach')?.addEventListener('click',()=>undo(d));
}
function add(role,text){state.coach.messages.push({role,text:String(text),ts:new Date().toISOString()});state.coach.messages=state.coach.messages.slice(-30);save()}
function context(){const d=day(),program=typeof getActiveProgram==='function'?getActiveProgram():null;return{profile:state.coach.profile,program:{id:program?.id||state.programId,name:program?.name||'Current program',week:state.week,progress:typeof getProgramProgressFor==='function'?getProgramProgressFor():null},selectedDay:d,selectedWorkout:getWorkoutsForDay(d).map(({phase,exercise,sets,reps,rest,tempo,notes,equipment})=>({phase,exercise,sets,reps,rest,tempo,notes,equipment})),recentHistory:(typeof getWorkoutHistory==='function'?getWorkoutHistory():[]).slice(-60).map(({ts,exercise,weight,reps,sets})=>({date:ts,exercise,weight:weight||null,reps:reps||null,sets:sets||null})),recentBodyWeight:(typeof getWeightLog==='function'?getWeightLog():[]).slice(-8).map(({ts,weight})=>({date:ts,weight}))}}
async function send(){
 if(busy)return;const input=document.getElementById('coachInput'),text=input?.value.trim();if(!text)return;if(!state.coach.privacyAccepted)return alert('Accept the Gemini testing notice first.');if(!currentSyncKey)return alert('Sign in to sync before using Coach.');add('user',text);state.coach.proposal=null;busy=true;render();
 try{const conversation=state.coach.messages.slice(-12,-1).filter(x=>['user','assistant'].includes(x.role)).map(({role,text})=>({role,text}));const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${ANON}`,apikey:ANON,'x-coach-user':currentSyncKey},body:JSON.stringify({message:text,conversation,context:context()})});const p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p.error||`Request failed (${r.status})`);add('assistant',p.reply||'I reviewed your workout.');if(valid(p.proposal)){state.coach.proposal=p.proposal;save()}}
 catch(e){console.error(e);let t=String(e.message||e);if(/GEMINI_API_KEY|not configured/i.test(t))t='The coach is installed, but its Gemini API key is not configured yet.';else if(/429|quota|rate/i.test(t))t='The Gemini testing limit was reached. Try again after it resets.';else if(/fetch|network/i.test(t))t='The coach backend could not be reached.';add('error',t)}finally{busy=false;render()}
}
function valid(p){return p&&DAYS.includes(p.day)&&Array.isArray(p.exercises)&&p.exercises.length&&p.exercises.length<=30&&p.exercises.every(e=>e?.exercise&&e?.phase)}
const norm=e=>({phase:String(e.phase||'Main Workout'),exercise:String(e.exercise),sets:String(e.sets||'3'),reps:String(e.reps||'10'),rest:Math.max(0,Math.min(300,parseInt(e.rest,10)||0)),tempo:String(e.tempo||'Controlled'),notes:String(e.notes||''),equipment:String(e.equipment||'Bodyweight')});
function prefixes(d){const p=typeof getActiveProgramId==='function'?getActiveProgramId():state.programId;return[`w${state.week}_${p}_${d}_`,`w${state.week}_${d}_`]}
function pullStates(d){const out={};Object.keys(state.data||{}).forEach(k=>{if(prefixes(d).some(p=>k.startsWith(p))){out[k]=clone(state.data[k]);delete state.data[k]}});return out}
function apply(){const p=state.coach.proposal;if(!valid(p)||!confirm(`Replace your ${p.day} workout with this coach plan?`))return;const k=key(p.day);state.coach.undo={key:k,day:p.day,previous:state.coachOverrides[k]?clone(state.coachOverrides[k]):null,exerciseState:pullStates(p.day)};state.coachOverrides[k]={title:p.title,reason:p.reason,exercises:p.exercises.map(norm),createdAt:new Date().toISOString(),provider:'gemini'};state.coach.proposal=null;save();if(state.day===p.day)renderDay(p.day);updateWeekHeader?.();render()}
function undo(d){const k=key(d);if(!state.coachOverrides[k]||!confirm(`Restore the original ${d} workout?`))return;pullStates(d);delete state.coachOverrides[k];const u=state.coach.undo;if(u?.key===k){if(u.previous)state.coachOverrides[k]=u.previous;Object.assign(state.data,u.exerciseState||{});state.coach.undo=null}save();if(state.day===d)renderDay(d);updateWeekHeader?.();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
