const ORIGINS=new Set(['https://joeybukowski3.github.io','http://localhost:3000','http://localhost:5173','capacitor://localhost']);
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const schema={type:'object',additionalProperties:false,properties:{reply:{type:'string'},proposal:{type:'object',additionalProperties:false,properties:{day:{type:'string',enum:DAYS},title:{type:'string'},reason:{type:'string'},exercises:{type:'array',minItems:1,maxItems:30,items:{type:'object',additionalProperties:false,properties:{phase:{type:'string'},exercise:{type:'string'},sets:{type:'string'},reps:{type:'string'},rest:{type:'integer',minimum:0,maximum:300},tempo:{type:'string'},notes:{type:'string'},equipment:{type:'string'}},required:['phase','exercise','sets','reps','rest','tempo','notes','equipment']}}},required:['day','title','reason','exercises']}},required:['reply']};
function cors(origin:string|null){return{'Access-Control-Allow-Origin':origin&&ORIGINS.has(origin)?origin:'https://joeybukowski3.github.io','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-coach-user','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}}
function reply(body:unknown,status:number,origin:string|null){return new Response(JSON.stringify(body),{status,headers:{...cors(origin),'Content-Type':'application/json','Cache-Control':'no-store'}})}
const clean=(v:unknown,n=5000)=>String(v??'').replace(/\u0000/g,'').slice(0,n);
async function profileExists(syncKey:string){
 if(Deno.env.get('COACH_SKIP_PROFILE_CHECK')==='true')return true;
 const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)throw Error('Supabase service credentials unavailable.');
 const r=await fetch(`${url}/rest/v1/sync_data?sync_key=eq.${encodeURIComponent(syncKey)}&select=sync_key&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw Error(`Profile verification failed (${r.status}).`);const rows=await r.json();return Array.isArray(rows)&&rows.length>0;
}
async function limit(syncKey:string){
 const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return;const date=new Date().toISOString().slice(0,10),h={apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'};
 const q=await fetch(`${url}/rest/v1/coach_usage?sync_key=eq.${encodeURIComponent(syncKey)}&usage_date=eq.${date}&select=request_count&limit=1`,{headers:h});if(!q.ok){console.warn('coach_usage unavailable');return}const rows=await q.json(),count=Number(rows?.[0]?.request_count||0);if(count>=100)throw Object.assign(Error('Daily coach request limit reached.'),{name:'RateLimitError'});
 await fetch(`${url}/rest/v1/coach_usage?on_conflict=sync_key,usage_date`,{method:'POST',headers:{...h,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({sync_key:syncKey,usage_date:date,request_count:count+1,updated_at:new Date().toISOString()})});
}
function prompt(message:string,conversation:any[],context:any){return`You are the AI Workout Coach inside a personal workout tracker.
Use the supplied program, current workout and recent history instead of generic advice. Be supportive, direct and concise.
Priorities: chest, biceps and core development; gradual fat loss; flexibility, mobility and knee stability.
Constraints: prior ACL tear and meniscus surgery; avoid jumping, quick lateral movement, deep knee flexion, free-weight squats and heavy isolated knee pressure; favor controlled low-impact Planet Fitness machines, cables, Smith machine, stable bodyweight work and knee-safe posterior-chain/hip work.
Do not diagnose or provide medical treatment. For sharp pain, swelling, locking, instability, new injury or concerning symptoms, advise stopping the aggravating movement and consulting an appropriate medical professional.
Only include proposal when the user requests or clearly needs a schedule adjustment. A proposal must be the COMPLETE replacement workout for one day, including warm-up/cooldown when appropriate. Never claim it was applied; the user must approve it. Rest is integer seconds; sets and reps are strings. Keep equipment realistic for Planet Fitness.
The name, PIN and sync key are intentionally absent; never request them.
CONTEXT:${JSON.stringify(context)}
RECENT CONVERSATION:${conversation.map(x=>`${x.role.toUpperCase()}: ${x.text}`).join('\n')||'none'}
USER:${message}
Return only JSON matching the response schema.`}
function textOf(x:any):string{if(!x)return'';if(typeof x.output_text==='string')return x.output_text;if(typeof x.outputText==='string')return x.outputText;if(typeof x.text==='string')return x.text;const c=x.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||'').join('');if(c)return c;for(const k of['outputs','output','content','parts','messages','steps']){const v=x[k];if(Array.isArray(v)){for(const i of v){const t=textOf(i);if(t)return t}}else if(v&&typeof v==='object'){const t=textOf(v);if(t)return t}}return''}
function parsed(t:string){const s=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');try{return JSON.parse(s)}catch{const a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)return JSON.parse(s.slice(a,b+1));throw Error('Gemini returned unreadable JSON.')}}
function normalized(v:any){if(!v||typeof v.reply!=='string')throw Error('Gemini returned an invalid response.');const out:any={reply:clean(v.reply,8000)},p=v.proposal;if(p&&DAYS.includes(p.day)&&Array.isArray(p.exercises)&&p.exercises.length)out.proposal={day:p.day,title:clean(p.title,160),reason:clean(p.reason,600),exercises:p.exercises.slice(0,30).map((e:any)=>({phase:clean(e.phase,80)||'Main Workout',exercise:clean(e.exercise,160)||'Exercise',sets:clean(e.sets,40)||'3',reps:clean(e.reps,60)||'10',rest:Math.max(0,Math.min(300,parseInt(e.rest,10)||0)),tempo:clean(e.tempo,60)||'Controlled',notes:clean(e.notes,500),equipment:clean(e.equipment,100)||'Bodyweight'}))};return out}
Deno.serve(async req=>{
 const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(req.method!=='POST')return reply({error:'Method not allowed.'},405,origin);if(origin&&!ORIGINS.has(origin))return reply({error:'Origin not allowed.'},403,origin);
 try{
  if(Number(req.headers.get('content-length')||0)>100000)return reply({error:'Request too large.'},413,origin);
  const syncKey=clean(req.headers.get('x-coach-user'),120).trim();if(!syncKey||!/^[a-zA-Z0-9._-]+$/.test(syncKey))return reply({error:'Sign in to sync before using Coach.'},401,origin);if(!await profileExists(syncKey))return reply({error:'Synced profile not found.'},401,origin);await limit(syncKey);
  const apiKey=Deno.env.get('GEMINI_API_KEY');if(!apiKey)return reply({error:'GEMINI_API_KEY is not configured.'},503,origin);
  const b=await req.json(),message=clean(b?.message,2000).trim();if(!message)return reply({error:'Message required.'},400,origin);const conversation=Array.isArray(b?.conversation)?b.conversation.slice(-12).filter((x:any)=>['user','assistant'].includes(x?.role)).map((x:any)=>({role:x.role,text:clean(x.text,2000)})):[];const context=b?.context&&typeof b.context==='object'?b.context:{};if(JSON.stringify(context).length>80000)return reply({error:'Workout context too large.'},413,origin);
  const r=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({model:Deno.env.get('GEMINI_MODEL')||'gemini-3.1-flash-lite',input:prompt(message,conversation,context),response_format:{type:'text',mime_type:'application/json',schema}})});const data=await r.json().catch(()=>({}));if(!r.ok){console.error(data);return reply({error:data?.error?.message||`Gemini request failed (${r.status}).`},r.status===429?429:502,origin)}const text=textOf(data);if(!text)return reply({error:'Gemini returned an empty response.'},502,origin);return reply(normalized(parsed(text)),200,origin);
 }catch(e){console.error(e);if(e instanceof Error&&e.name==='RateLimitError')return reply({error:e.message},429,origin);return reply({error:e instanceof Error?e.message:'Unexpected coach error.'},500,origin)}
});
